# Generated by Django 3.1.7 on 2021-07-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avaters/avatars.jpg', upload_to='avaters'),
        ),
    ]
